'use client';

import { useState, useEffect } from 'react';
import { AlertTriangle, X } from 'lucide-react';

const STORAGE_KEY = 'ai_disclaimer_dismissed';

export default function AIDisclaimer() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    // Show the banner unless the user dismissed it this session
    const dismissed = sessionStorage.getItem(STORAGE_KEY);
    if (!dismissed) setVisible(true);
  }, []);

  const dismiss = () => {
    setVisible(false);
    sessionStorage.setItem(STORAGE_KEY, '1');
  };

  if (!visible) return null;

  return (
    <div className="relative bg-yellow-500/10 border border-yellow-500/30 rounded-xl px-4 py-3 flex items-start gap-3 animate-in fade-in duration-300">
      <AlertTriangle className="w-5 h-5 text-yellow-400 shrink-0 mt-0.5" />
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-yellow-300">
          AI/ML Prediction Disclaimer
        </p>
        <p className="text-xs text-yellow-200/70 mt-0.5 leading-relaxed">
          All predictions are generated by artificial intelligence and machine learning models. 
          AI can and does make mistakes — predictions are <span className="font-semibold text-yellow-200">not financial advice</span>. 
          Past performance does not guarantee future results. 
          Always do your own research and invest at your own risk.
        </p>
      </div>
      <button
        onClick={dismiss}
        className="shrink-0 p-1 rounded-md hover:bg-yellow-500/20 transition-colors"
        aria-label="Dismiss"
      >
        <X className="w-4 h-4 text-yellow-400" />
      </button>
    </div>
  );
}
